config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'pages#home'

  # resources :users, only: %i[show profile update]
  resources :profiles, only: %i[update show edit] do
    collection do
      get :my_boats
      get :my_requests
    end
  end

  # post '/boats/search', to: 'boats#index', as: :boats_search

  resources :boats do
      resources :bookings, only: %i[new create show edit update]
      resources :reviews, only: %i[new create]
  end

  resources :bookings, only: :index

  resources :conversations do
    resources :messages
  end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :boats, only: [ :index ]
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[show edit update my_requests]

  def my_boats
    @boats = Boat.where(user: current_user.id)
    authorize @boats
  end

  def my_requests
    authorize @user
  end

  def index
    @boats = Boat.where(user: current_user.id)
    @booking = @boats.booking
  end

  def show
    authorize @user
    @boats = Boat.where(user: current_user.id)
    @boat = Boat.find_by(user: current_user.id)
    @user = User.find(current_user.id)
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(profile_user_params)
      redirect_to profile_path(current_user.id)
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def profile_user_params
    params.require(:user).permit(:name, :email, :bio, :photo)
  end
end

app/views/profiles/my_boats.html.erb
<div class="container">
  <h1>Here I should see my boats Only:</h1>
  <% @boats.each do |boat| %>
    <h2><%= link_to boat.name, boat_path(boat) %></h2>
  <% end %>
</div>

app/views/profiles/my_requests.html.erb
<% if @user.boats.all? { |boat| boat.bookings.count.zero? } %>
  <div class="titles-no-bookings">
    <h2>My Requests</h2>
    <%= render 'shared/tabs' %>
    <p>When you’re ready to start planning your next trip, we’re here to help. <%= link_to 'Learn more', "#"  %></p>
  </div>
  <div class="bg-no-requests">
    <div class="no-bookings-text">
      <div><h2>Relax, someone will book your boat soon!</h2></div>
      <div><%= link_to 'Get Started', boats_path, class: "btn btn-primary"  %></div>
    </div>
  </div>

  <% else %>
    <div class="container">
    <div class="row">
      <div>
        <h2>My Requests</h2>
        <%= render 'shared/tabs' %>
        <% my_count = @user.boats.map { |boat| boat.bookings.count } %>
        <p>You have <%= pluralize my_count.sum, 'request' %> </p>
      </div>
    </div>

    <% @user.boats.each do |boat| %>
      <% if boat.bookings.count.positive? %>
        <% boat.bookings.each do |booking| %>
          <div class="card-product mb-3">
            <% if boat.photo.attached? %>
              <%= cl_image_tag boat.photo.key%>
            <% else %>
              <%= cl_image_tag "add-new-boat_copy_g6t5lo"%>
            <% end %>
            <div class="card-product-infos d-flex" style="justify-content: space-between;flex-grow: 1;">
              <div>
                <h4><%= link_to boat.name, boat_path(boat) %> <%= booking.status %></h4>
                <p>From <strong><%= booking.checkin.strftime("%d %b") %></strong> to <strong><%= booking.checkout.strftime("%d %b") %></strong></p>
                <p>by <%= User.find_by(id: booking.user_id).name %></p>
              </div>
              <div class="d-flex flex-direction-column" style="flex-direction: column;justify-content: space-between;">
                <button type="button" class="btn btn-primary"><%= link_to 'Accept', boat_booking_path(booking.boat, booking, booking:{ status:"approved" }), method: :patch %></button>
                <button type="button" class="btn btn-secondary"><%= link_to 'Reject', boat_booking_path(booking.boat, booking, booking:{ status:"rejected" }), method: :patch %></button>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <div>
      <p><%= link_to 'Back to my profiles', profile_path(@user) %></p>
    </div>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="profile-show-container" style="height: 1100px">
  <div class="profile-show-menu" style="z-index: 1;">
    <div class="profile-menu">
      <p id="btn-profile" class="dropdown-item" style="display: flex;align-items: center; text-align: start; cursor: pointer; padding: 0;"><i class="fas fa-user-alt" style="margin-right: 24px;"></i> Profile </p>
      <p id="btn-boat" class="dropdown-item" style="display: flex;align-items: center; text-align: start; cursor: pointer; padding: 0;"><i class="fas fa-ship" style="margin-right: 24px;"></i>My Boats</p>
      <!-- <p style="display: flex;align-items: center; text-align: start"><i class="fas fa-user-alt"></i><%= link_to "Profile", profile_path(@user), class: "dropdown-item" %></p> -->
      <!-- <p style="display: flex;align-items: center; text-align: start"><i class="fas fa-ship"></i><%= link_to "Boats", my_boats_profiles_path, class: "dropdown-item" %></p> -->
      <p style="display: flex;align-items: center; text-align: start"><i class="fas fa-inbox"></i><%= link_to "Requests", my_requests_profiles_path, class: "dropdown-item" %></p>
      <p style="display: flex;align-items: center; text-align: start"><i class="far fa-calendar-alt"></i><%= link_to "Bookings", bookings_path, class: "dropdown-item" %></p>
    </div>
    <div class="profile-menu">
      <p style="display: flex;align-items: center; text-align: start"><i class="fas fa-user-cog"></i><%= link_to "Settings", "#", class: "dropdown-item" %></p>
      <p style="display: flex;align-items: center; text-align: start"><i class="fas fa-info-circle"></i><%= link_to "More Info", "#", class: "dropdown-item" %></p>
      <p style="display: flex;align-items: center; text-align: start"><i class="fas fa-lock"></i><%= link_to "Privacy", "#", class: "dropdown-item" %></p>
      <p style="display: flex;align-items: center; text-align: start"><i class="fas fa-sign-out-alt"></i><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></p>
    </div>

  </div>
  <%= render 'shared/profile_show_modal' %>
</div>


<!-- Modal Pop-Up -->
<!-- Here are located all the pop-up windows -->

<div class="bg-modal">
  <div class="modal-content">
    <div class="close">+</div>
    <%#= render 'shared/edit_profile_picture' %>
  </div>
</div>

<div class="my-boats-modal">
  <div class="boats-modal-content">
    <%= render 'shared/my_boats_profile' %>
  </div>
</div>

<%= render 'shared/footer' %>

<!-- <p><%#= @user.name %> has <%= @user.boats.count %> boats</p>
<%#= link_to 'See Boats', my_boats_profiles_path %>
<hr>
<p><%#= @user.name %> has <%= @user.bookings.count %> Bookings</p>
<%#= link_to 'See Bookings', bookings_path %>
<hr>

<%# bookings_count = [] %>
<%# @user.boats.each do |boat| %>
  <%# bookings_count << boat.bookings.count %>
<%# end %>
<p>You have <%#= bookings_count.sum %> requests</p>
<%#= link_to 'See Requests', my_requests_profiles_path %>

<hr>
<p>Bio:</p>
<%#= @user.bio %>
<hr>