config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'pages#home'

  # resources :users, only: %i[show profile update]
  resources :profiles, only: %i[update show edit] do
    collection do
      get :my_boats
      get :my_requests
    end
  end

  # post '/boats/search', to: 'boats#index', as: :boats_search

  resources :boats do
      resources :bookings, only: %i[new create show edit update]
      resources :reviews, only: %i[new create]
  end

  resources :bookings, only: :index

  resources :conversations do
    resources :messages
  end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :boats, only: [ :index ]
    end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat

  validates :checkin, :checkout, presence: { message: "Please select the date." }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: %i[show edit update]
  before_action :find_boat, only: %i[new create show edit]
  before_action :authenticate_user!, only: %i[new create]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @bookings = policy_scope(Booking).order(checkin: :asc)
  end

  def new
    @booking = Booking.new
    authorize @booking
    @unavailable_dates = Booking.where(boat_id: @boat.id).map do |booking|
      { from: booking.checkin, to: booking.checkout }
    end
    # when we have a method for accepting a booking, we should change so that only accepted booking dates are disabled
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.boat = @boat
    @booking.status = "pending"

    @booking.booking_price = @boat.price * (@booking.checkout - @booking.checkin).to_i / (24 * 60 * 60)
    authorize @booking
    if @booking.save
      redirect_to boat_booking_path(@boat, @booking)
    else
      render :new
    end
  end

  def show
    @markers =
      {
        lat: @booking.boat.latitude,
        lng: @booking.boat.longitude
      }
    authorize @booking
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    @booking.update(booking_params)
    redirect_to boat_booking_path(@booking.boat)
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:checkin, :checkout, :status, :booking_price)
  end

  def find_boat
    @boat = Boat.find(params[:boat_id])
  end
end

app/views/bookings/_form.html.erb
<div class="container ml-3" id='disable-unavailable-dates' data-dates='<%= @unavailable_dates.to_json %>'>
  <h3>Book this boat!</h3>
  <%= simple_form_for [@boat, @booking] do |f| %>
    <%= f.input :checkin, as: :string, input_html: {class: 'datepicker', type: 'hidden'} %>
    <%= f.input :checkout, as: :string, input_html: {class: 'datepicker', type: 'hidden'} %>
    <%= f.submit class:'btn btn-primary'%>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<%= render "form", booking: @booking %>

app/views/bookings/index.html.erb
<% if @bookings.count != 0 %>
  <div class="container">
    <div class="row">
        <div style="margin-top: 5%;">
          <h2>My Sails</h2>
          <%= render 'shared/tabs' %>
        </div>

        <div class="grid-boats" style="display: grid;grid-template-columns: 1fr 1fr 1fr; grid-gap: 16px;">
          <% @bookings.each do |booking| %>
          <%= link_to (boat_booking_path(booking.boat, booking)) do  %>
            <div class="card-booking">
              <% if booking.boat.photo.attached? %>
                <%= cl_image_tag booking.boat.photo.key, crop: :fill, class:'card-img-top', alt:'Card image cap'%>
              <% else %>
                <%= cl_image_tag "add-new-boat_copy_g6t5lo", crop: :fill, class:'card-img-top', alt:'Card image cap'%>
              <% end %>
              <div class="card-booking-infos">
                <div>
                  <p class="checkin-checkout"><%= booking.checkin.strftime("%d %b") %> - <%= booking.checkout.strftime("%d %b") %> </p>
                  <h2 class="booking-boat"><%= booking.boat.name %></h2>
                  <p class="booking-price"><%= booking.booking_price %> EUR</p>
                </div>
                <h2 class="card-booking-status badge badge-pill badge-light" id="<%= booking.status %>"><%= booking.status %></h2>
              </div>
            </div>
          <% end %>
          <% end %>
        </div>

    </div>
  </div>
<% else %>
  <div class="titles-no-bookings">
    <h2>My Sails</h2>
    <%= render 'shared/tabs' %>
    <p>When you’re ready to start planning your next trip, we’re here to help. <%= link_to 'Learn more', "#"  %></p>
  </div>
  <div class="bg-no-bookings">
    <div class="no-bookings-text">
      <div><h2>Ready to use our service?</h2></div>
      <div><%= link_to 'Get Started', boats_path, class: "btn btn-primary"  %></div>
    </div>
  </div>
<% end %>

app/views/bookings/new.html.erb
<%= render "form", booking: @booking %>

app/views/bookings/show.html.erb
<div class="container">
  <h1 class="text-center" style="margin-top: 5%;"><strong>Your sail with <%= @booking.boat.name %></strong></h1>

  <div class="container p-3">
    <div class="row row-booking-show">
      <div class="col-md-6">
      <% if @booking.boat.photo.attached? %>
        <%= cl_image_tag @booking.boat.photo.key, class: "card-category" %>
      <% else %>
        <%= cl_image_tag "add-new-boat_copy_g6t5lo"  %>
      <% end %>
      <div class="booking-status">
      <h2 class="card-booking-status badge badge-pill badge-light" id="<%= @booking.status %>"><%= @booking.status %></h2>
      </div>

      <div class="card border border-white">

        <div class="card-body">
          <h3 class="card-title"><%= link_to @booking.boat.name, boat_path(@booking.boat) %></h3>
          <h5 class="card-text"><%= @booking.boat.description %></h5>
        </div>
        <ul class="list-group list-group-flush">

          <li class="list-group-item d-flex justify-content-between">
            <div class="col checkin">
              <div class="booking-tabindex"><h6>Check-in</h6></div>
              <div><h3><%= @booking.checkin.strftime("%a, %d %b") %></h3></div>
            </div>

            <div class="col checkout">
              <div class="booking-tabindex"><h6>Check-out</h6></div>
              <div><h3><%= @booking.checkout.strftime("%a, %d %b") %></h3></div>
            </div>
          </li>

          <li class="list-group-item d-flex justify-content-between">
            <div class="col overview">
              <div class="booking-tabindex"><h6>Overview</h6></div>
              <div>
                <h5>Owned by <%= link_to @booking.boat.user.name, profile_path(@booking.boat.user) %></h5>
                <h5>max <%= @booking.boat.capacity %> people</h5>
                <h5>€ <%= @booking.booking_price %></h5>
              </div>
            </div>
              <% if @booking.boat.user.photo.attached? %>
                <%= cl_image_tag @booking.boat.user.photo.key, class: "avatar" %>
              <% else %>
                <%= cl_image_tag "add-new-boat_copy_g6t5lo", class: "avatar"  %>
              <% end %>
          </li>

          <li class="list-group-item d-flex justify-content-between">
            <div class="col who">
              <div class="booking-tabindex"><h6>Who's coming?</h6></div>
              <div>
                <h5><%= link_to @booking.user.name, profile_path(@booking.user) %></h5>
              </div>
            </div>
              <% if @booking.user.photo.attached? %>
                <%= cl_image_tag @booking.user.photo.key, class: "avatar" %>
              <% else %>
                <%= cl_image_tag "avatar_default.jpg", class: "avatar"  %>
              <% end %>
          </li>

          <li class="list-group-item d-flex justify-content-between">
            <div class="col location">
              <div class="booking-tabindex"><h6>Where?</h6></div>
              <div>
                <h4><%= @booking.boat.location %></h4>
              </div>
            </div>
          </li>

          <%= link_to '#' do %>
          <li class="list-group-item d-flex justify-content-between list-link">
            <div class="col icon">
              <div><i class="fas fa-print"></i></div>
            </div>
            <h5>Print details</h5>
          </li>
          <% end %>

          <%= link_to '#' do %>
          <li class="list-group-item d-flex justify-content-between list-link">
            <div class="col icon">
              <div><i class="fas fa-receipt"></i></div>
            </div>
            <h5>Get a receipt</h5>
          </li>
          <% end %>

      <% if current_user %>
        <% unless policy(@booking.boat).edit?%>

          <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @boat.user.id), method: "post" do  %>
          <li class="list-group-item d-flex justify-content-between list-link">
            <div class="col icon">
              <div><i class="fas fa-comment-alt"></i></div>
            </div>
            <h5>Contact Owner</h5>
          </li>
          <% end %>

          <%= link_to new_boat_review_path(@boat) do  %>
          <li class="list-group-item d-flex justify-content-between list-link">
            <div class="col icon">
              <div><i class="fas fa-pen"></i></div>
            </div>
            <h5>Review this boat</h5>
          </li>
          <% end %>
        <% end %>
        <% end %>
      </ul>

      <div class="row d-flex justify-content-center">
        <% unless @booking.status == "cancelled" %>
          <% if policy(@booking).edit? %>
            <button type="button" class="btn btn-light booking-show-button"><%= link_to "Update", edit_boat_booking_path(@boat) %></button>
          <% end %>
            <button type="button" class="btn btn-light booking-show-button"><%= link_to 'Cancel the booking', boat_booking_path(@booking, booking:{ status:"cancelled" }), method: :patch %></button>
        <% end %>
        <button type="button" class="btn btn-light booking-show-button"><%= link_to 'Back to all bookings', bookings_path %></button>
      </div>

      </div>
    </div>

      <div class="col-md-6">
        <div class="map-booking-show" id="booking-map"
            style="width: 100%; height: 1000px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key='<%= ENV['MAPBOX_API_KEY'] %>'></div>
      </div>
    </div>
</div>