config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'pages#home'

  # resources :users, only: %i[show profile update]
  resources :profiles, only: %i[update show edit] do
    collection do
      get :my_boats
      get :my_requests
    end
  end

  # post '/boats/search', to: 'boats#index', as: :boats_search

  resources :boats do
      resources :bookings, only: %i[new create show edit update]
      resources :reviews, only: %i[new create]
  end

  resources :bookings, only: :index

  resources :conversations do
    resources :messages
  end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :boats, only: [ :index ]
    end
  end
end

app/views/shared/_chat_form.html.erb
<%= form_for [@conversation, @message] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control" %>
  </div>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
  <div class="form-group">
    <%= f.submit "Send Reply", class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_chat_messages.html.erb
<div>
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
        <div class="chat-box">
          <% if message.user.id == current_user.id  %>
            <div class="message-body-sender" style="text-align: end;">
              <%= message.body %>
              <p><%= message.created_at.strftime(" %l:%M") %></p>
            </div>
          <% else %>
            <div class="message-body-recipient" style="text-align: start;">
              <p><%= message.created_at.strftime(" %l:%M") %></p>
              <%= message.body %>
            </div>
          <% end %>
        </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_chat_navbar.html.erb
<div class="chat-container">
  <% @conversation.each do |conversation| %>
    <%= link_to conversation_messages_path(conversation) do %>
      <div class="message-container d-flex">
        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
          <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = User.find(conversation.sender_id) %>
          <% end %>
          <div class="d-flex" style="flex-grow: 1;">
            <div class="message-user-avatar">
              <%= cl_image_tag recipient.photo.key, height: 70, width: 70, crop: :fill  %>
            </div>
            <div class="message-content">
              <div class="chat-username"><%= recipient.name %></div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_dropdown_personal.html.erb
<div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Personal
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Profile</a>
    <a class="dropdown-item" href="#">My Boats</a>
    <a class="dropdown-item" href="#">Request</a>
    <a class="dropdown-item" href="#">Bookings</a>
    <%= link_to 'Edit Profile', edit_user_registration_path(current_user.id), class: "dropdown-item" %>
  </div>
</div>

app/views/shared/_edit_profile_picture.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-5 col-sm-5" style="margin: auto;">

      <h2>Edit <%= resource_name.to_s.humanize %></h2>

      <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :photo, as: :file %>
          <%= f.input :current_password,
                      hint: "We need your current password to confirm your changes",
                      required: true,
                      input_html: { autocomplete: "current-password" } %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Update", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">
  <div class="footer-titles">
    <p style="text-align: end;"><%= link_to "Impressum", "#"  %></p>
    <p class="company-title" style="margin-bottom: 40px;"><%= link_to "Boatbnb", "#"  %></p>
    <p class="help-title"><%= link_to "Help Center", "#"  %></p>
  </div>
  <div class="footer-data d-flex">
    <div>
      <ul>
        <h4>Company</h4>
        <li><%= link_to 'About us', '#'  %></li>
        <li><%= link_to 'Blog', '#'  %></li>
        <li><%= link_to 'Investors', '#'  %></li>
        <li><%= link_to 'Careers', '#'  %></li>
        <li><%= link_to 'Newsroom', '#'  %></li>
      </ul>
    </div>
    <div>
      <ul>
        <h4>Community</h4>
        <li><%= link_to 'Boatbnb Magazine', '#'  %></li>
        <li><%= link_to 'Invite Friends', '#'  %></li>
        <li><%= link_to 'Gift Cards', '#'  %></li>
        <li><%= link_to 'Safety', '#'  %></li>
        <li><%= link_to 'Diversity', '#'  %></li>
      </ul>
    </div>
    <div>
      <ul>
        <h4>Products</h4>
        <li><%= link_to 'Boats', '#'  %></li>
        <li><%= link_to 'Captains', '#'  %></li>
        <li><%= link_to 'Policy', '#'  %></li>
        <li><%= link_to 'Open Sea', '#'  %></li>
      </ul>
    </div>
    <div>
      <ul>
        <h4>Support</h4>
        <li><%= link_to 'Updates for COVID-19', '#'  %></li>
        <li><%= link_to 'Cancellation Options', '#'  %></li>
        <li><%= link_to 'Investors', '#'  %></li>
        <li><%= link_to 'Transparency', '#'  %></li>
        <li><%= link_to 'Boatbnb for Business', '#'  %></li>
      </ul>
    </div>
  </div>
  <div class="footer-social">
    <div class="social-links">
      <ul>
        <li><%= link_to '<i class="fab fa-twitter"></i>'.html_safe, '#' %></li>
        <li><%= link_to '<i class="fab fa-facebook-square"></i>'.html_safe, '#' %></li>
        <li><%= link_to '<i class="fab fa-youtube"></i>'.html_safe, '#' %></li>
        <li><%= link_to '<i class="fab fa-linkedin"></i>'.html_safe, '#' %></li>
        <li><%= link_to '<i class="fab fa-instagram"></i>'.html_safe, '#' %></li>
        <li><%= link_to '<i class="fas fa-globe-americas"></i> English'.html_safe, '#' %></li>
        <li><%= link_to '<i class="fas fa-map-marker-alt"></i> Berlin'.html_safe, '#' %></li>
      </ul>
    </div>
    <div class="copyrights">
      <p style="margin: 0; margin-top: 50px;">© 2020 Boatbnb Inc. All rights reserved</p>
    </div>
  </div>
</div>

app/views/shared/_my_boats.html.erb
<div id="content-index" class="ml-3 pl-3 mr-3 pr-3">
  <div class="grid-boats-profile">
    <% @boats.each do |boat| %>
      <div class="card-product" id="boat-index">
        <%= cl_image_tag boat.photo.key, height: 100, width: 100, crop: :fill %>
        <div class="card-product-infos" id="boat-index-infos">
          <h1><%= link_to boat.name, boat_path(boat) %></h1>
          <p><%= boat.description %></p>
        </div>
        <div id="reviews-boat-index">
          <p>⭐️</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_my_boats_profile.html.erb
<div class="myboats-profile-container ml-3 pl-3 mr-3 pr-3">
  <div class="grid-myboats">
    <% @boats.each do |boat| %>
      <div class="myboat-card">
        <% if boat.photo.attached? %>
          <%= cl_image_tag boat.photo.key, height: 210, width: 210, crop: :fill %>
        <% else %>
          <%= cl_image_tag 'add-new-boat_agnmrs', height: 210, width: 210, crop: :fill %>
        <% end %>
        <div class="mt-4 myboat-card-info d-flex justify-content-between align-items-center">
          <h4><%= link_to boat.name, boat_path(boat) %></h4>
          <p><%= link_to 'Info', boat_path(boat)  %></p>
        </div>
      </div>
    <% end %>
    <div class="myboat-card-new">
      <%#= image_tag "add-new-boat", alt: "boat-new", height: 210, width: 210, crop: :fill %>
      <h4 style="text-align: center; margin-top: 240px;"><%= link_to "Add new boat", new_boat_path, class: "btn btn-primary" %></h4>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="z-index: 2;">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="d-flex">
      <%= image_tag "logo.png", class: "heigth-logo"%>
      <div class="d-flex ml-3 slogan">
        <h1>Ahoy! Adventure</h1>
      </div>
    </div>
  <% end %>

    <%#= image_tag("slogan.png", :class => "slogan")%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Messages", conversations_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add a Boat", new_boat_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <p class="nav-link"><%= current_user.name %></p>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "avatar_default.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", bookings_path , class: "dropdown-item" %>
            <% unless current_user.boats.nil? %>
              <%= link_to "My Requests", my_requests_profiles_path(current_user), class: "dropdown-item"  %>
            <% end %>
            <% if policy(User).show? %>
              <%= link_to "Profile", profile_path(current_user.id), class: "dropdown-item" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_profile_show_modal.html.erb
<div id="profile-show-modal" class="profile-show-modal">
  <h4>Welcome on board <strong><%= @user.name.split.first %></strong>!</h4>
  <div class="profile-cover-picture">
    <%= cl_image_tag "profile-cover-picture_fihzo3" %>
  </div>
  <div class="profile-avatar" style="margin-right: 24px;position: relative;bottom: 45px;left: 45px;">
    <div class="profile-user-picture">
      <div id="profile-avatar"> <%= cl_image_tag @user.photo.key, width: 120, height: 120, crop: :fill %> </div>
      <div class="d-flex">
        <p style="font-size: 14px;"><%= link_to "Change", edit_user_registration_path %></p>
      </div>
    </div>
    <div class="profile-user-info" style="display: flex;flex-direction: column;justify-content: end;margin-bottom: 2%;margin-left: 2%;">
      <strong><h4><%= @user.name %></h4></strong>
      <div class="d-flex">
        <p style="margin-right: 24px"><%= @user.bio %></p>
        <p><i class="fas fa-map-marker-alt" style="color: #ff5f40; margin-right: 8px;"></i>Berlin, DE</p>
      </div>
    </div>
  </div>
  <div class="user-info">
    <div class="d-flex justify-content-between mx-5 py-1">
      <div class="d-flex grow-1">
        <div style="width: 150px;">
          <strong><p style="margin-right: 24px">Name</p></strong>
        </div>
        <div>
          <p><%= @user.name %></p>
        </div>
      </div>
      <p><%= link_to "Edit", edit_user_registration_path %></p>
    </div>
    <hr style="width: 90%">
    <div class="d-flex justify-content-between mx-5 py-1">
      <div class="d-flex grow-1">
        <div style="width: 150px;">
          <strong><p style="margin-right: 24px">Bio</p></strong>
        </div>
        <div>
          <p><%= @user.bio %></p>
        </div>
      </div>
      <p><%= link_to "Edit", edit_user_registration_path %></p>
    </div>
    <hr style="width: 90%">
    <div class="d-flex justify-content-between mx-5 py-1">
      <div class="d-flex grow-1">
        <div style="width: 150px;">
          <strong><p style="margin-right: 24px">E-mail</p></strong>
        </div>
        <div>
          <p><%= @user.email %></p>
        </div>
      </div>
      <p><%= link_to "Edit", edit_user_registration_path %></p>
    </div>
    <hr style="width: 90%">
    <div class="d-flex justify-content-between mx-5 py-1">
      <div class="d-flex grow-1">
        <div style="width: 150px;">
          <strong><p style="margin-right: 24px">City</p></strong>
        </div>
        <div>
          <p>Berlin, DE</p>
        </div>
      </div>
      <p><%= link_to "Edit", edit_user_registration_path %></p>
    </div>
    <hr style="width: 90%">
    <div class="d-flex justify-content-between mx-5 py-1">
      <div class="d-flex grow-1">
        <div style="width: 150px;">
          <strong><p style="margin-right: 24px">Password</p></strong>
        </div>
        <div>
          <p>* * * * * * * * * * </p>
        </div>
      </div>
      <p><%= link_to "Edit", edit_user_registration_path %></p>
    </div>
    <hr style="width: 90%">
    <div class="d-flex justify-content-between mx-5 py-1">
      <div class="d-flex grow-1">
        <div style="width: 150px;">
          <strong><p style="margin-right: 24px">Subscription Type</p></strong>
        </div>
        <div>
          <p><i class="fas fa-award" style="margin-right: 12px; color: gold"></i>Pro User</p>
        </div>
      </div>
      <p><%= link_to "Edit", edit_user_registration_path %></p>
    </div>
    <hr style="width: 90%">
    <div class="d-flex justify-content-between mx-5 py-1">
      <div class="d-flex grow-1">
        <div style="width: 150px;">
          <strong><p style="margin-right: 24px">Language</p></strong>
        </div>
        <div>
          <p>English</p>
        </div>
      </div>
      <p><%= link_to "Edit", edit_user_registration_path %></p>
    </div>
    <hr style="width: 90%">
  </div>
</div>

app/views/shared/_reviews.html.erb
<% rating = [] %>
<% if @boat.reviews.count != 0 %>
  <% @boat.reviews.each do |review| %>
    <% rating << review.rating %>
  <% end %>
  <% prom = rating.sum.to_f / @boat.reviews.count %>
  <% prom.to_i.times do  %>
    <i class="fas fa-star" style="color: #ffa931"></i>
  <% end %>
  <%= prom.round(1) %>
  <p>(<%= @boat.reviews.count %>)</p>
<% else %>
  <% puts "" %>
<% end %>

app/views/shared/_reviews_boat_show.html.erb
<div class="reviews-show-container">
  <% @boat.reviews.each do |review| %>
    <span class="review-container">
      <div class="reviews-left">
        <div class="review-user-avatar">
          <%= cl_image_tag review.user.photo.key, height: 120, width: 120, crop: :fill %>
        </div>
        <div class="review-user-name">
          <%= review.user.name %>
        </div>
      </div>

      <div class="reviews-right">
        <div class="title-content">
          <div class="reviw-rating">
            <% review.rating.to_i.times do  %>
              <i class="fas fa-star" style="color: #ffa931"></i>
            <% end %>
          </div>
          <div class="review-content">
            <%= review.content %>
          </div>
        </div>
        <div class="review-date">
          <p><%= review.created_at.strftime(" %l:%M - %d.%b.%y") %></p>
        </div>
      </div>
    </span>
  <% end %>
</div>

app/views/shared/_tabs.html.erb
<ul class="list-inline tabs-underlined">
  <li>
    <a href="#" class="tab-underlined active">Upcoming</a>
  </li>
  <li>
    <a href="#" class="tab-underlined">Past</a>
  </li>
</ul>